### ISSUE TITLE
Error in Aesthetics

### ISSUE THREAD

**Issue by chicothetanuki** [jamesepaterson/trackingworkshop#2]
Hello, I've strictly followed your code but I still got some error. It says 
"no non-missing arguments to min; returning Inf
no non-missing arguments to max; returning -Inf
no non-missing arguments to min; returning Inf
no non-missing arguments to max; returning -Inf
Removed 2369 rows containing missing values (geom_point).
"

This is when I try to run the code:

mymap.hr <- ggmap(mybasemap) + 
  geom_polygon(data = fortify(cat.mcpgeo),  
               # Polygon layer needs to be "fortified" to add geometry to the dataframe
              aes(long, lat, color = id, fill = id),
              alpha = 0.3) + # alpha sets the transparency
  geom_point(data = cat.geo, 
             aes(x = x, y = y, color = id))  +
  theme(legend.position = c(0.15, 0.80)) +
  labs(x = "Longitude", y = "Latitude") +
  scale_fill_manual(name = "Cat number", 
                      values = c("red", "blue", "purple", "orange"),
                      breaks = c("T001", "T002", "T003", "T004")) +
  scale_colour_manual(name = "Cat number", 
                      values = c("red", "blue", "purple", "orange"),
                      breaks = c("T001", "T002", "T003", "T004"))

I don't know what happens.

**Comment by jamesepaterson** [comment]
This issue is caused by your data set's x and y values. The error is indicating that you have coordinate values (x and y fields in object "cat.geo" and possibly others) that are NA.  Check that "cat.geo" and "fortify(cat.mcpgeo)" both do not have any missing values and have the correct field names you refer to in the call to aes().

Without seeing your earlier code, I cannot diagnose exactly why you're getting the error in this particular case. The code works on the example data set, so it is not an error in the code, but possibly in your data set or in the way you have changed the code.
